### PR TITLE
Add first events for 7/21 - Demo day and developer meeting

### PR DESCRIPTION
**Pull request by tonyfast**

### CODE REVIEW

**Review by richardotis — APPROVED** [review]

**Comment by richardotis** [comment]
Thanks Tony! What platform will be used to host the video portion of the meeting


________________________________

**Comment by tonyfast** [comment]
lets use jitsi for our first meeting: https://meet.jit.si/mgf-materials-science-demo-friday

lets make it a point to talk about discord for future events.

**Comment by tonyfast** [comment]
we'll need instructions for pre and post meeting work as we have these events. in the near term we'll let it evolve naturally and document after a few weeks.

**Comment by richardotis** [comment]
Okay. Am I remembering correctly that we're planning for 9am PT?

________________________________

**Comment by tonyfast** [comment]
i have the dev meeting at 8am PST and demo meeting at 9am PST. tomorrow we could just meet at 9. maybe we push the developer meeting for a week or two.. but not to collide with the board meeting.

**Comment by richardotis** [comment]
Just the demo day at 9am this week will be fine.

**Pull request merged**
